config/routes.rb
Rails.application.routes.draw do

  resources :updates

  devise_for :users

  root "updates#index"

end

app/models/update.rb
class Update < ActiveRecord::Base
  ## Relationships
  belongs_to :user


  ## Validations
  validates :user_id, presence: true

  validates :content, presence: true,
                      length: {
                        maximum: 60000
                      }


  ## Methods


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  ## Relationships
  has_many :updates#, dependent: :destroy


  ## Validations
  validates :email, presence: true

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                            with: /\A[a-zA-Z0-9\-\_\'\"\ ]+\Z/,
                            message: "Your unique, alphanumeric alias can contain the following characters: - _ \' \" "
                           }

  validates :gender, presence: true


  ## Methods
  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :profile_name, :gender]
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  before_action :set_update, only: [:show, :edit, :update, :destroy]

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: "Update was successfully created." }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <ul class="copyright">
    <li>&copy; Ali Esmaili</li>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<br>
<% flash.each do |type, mssg| %>
  <% if mssg.is_a?(String) %>
    <div data-alert class="alert-box round <%= type.to_s == "notice" ? "success" : "alert" %>">
      <%= content_tag :div, mssg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <!-- <li class="name">
      <%# link_to "Home", root_path %>
    </li> -->
    <li class="toggle-topbar menu-icon">
      <a href="#">Menu</a>
    </li>
  </ul>

  <div class="top-bar-section">
    <ul>
      <%= render "layouts/navigation_links" %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# navigation links %>
<nav class="top-bar">
  <ul class="title-area">
    <% if user_signed_in? %>
      <li class="name menu-icon">
        <%= link_to "Doppl", updates_path %>
      </li>
      <li class="name">
        <%= link_to "Edit Profile", edit_user_registration_path %>
      </li>
    <% end %>
  </ul>

  <ul class="title-area right">
    <% if user_signed_in? %>
      <li class="name">
        <%= link_to "Sign Out", destroy_user_session_path, method: :DELETE %>
      </li>
    <% else %>
      <li class="name">
        <%= link_to "Sign In", new_user_session_path %>
      </li>
      <li class="name">
        <%= link_to "Join Us", new_user_registration_path %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "Doppl" %></title>

    <%= stylesheet_link_tag    "application", media: "all", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "toolbar-16x16.png" %>
  </head>

  <body class="<%= "#{params[:controller].gsub("devise/", "") }" %>">
    <div class="container">
      <%= render "layouts/navigation" %>
      <%= render "layouts/messages" %>
    </div>

    <div class="wrapper">
      <%- if user_signed_in? %>
      <% end -%>

      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/updates/_form.html.erb
<div class="authform">
  <%= simple_form_for(@update) do |f| %>
    <% if @update.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h3>

        <ul>
        <% @update.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.input :user_id, collection: User.all, label_method: :full_name %>
      <%= f.input :content %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Update", :class => "button success radius right" %>
    </div>
  <% end %>
</div>

app/views/updates/edit.html.erb
<div class="edit-update">
  <h2>Edit Update</h2>
  <hr>

  <div class="back">
    <%= link_to "Back", updates_path, class: "button tiny round" %>
  </div>

  <%= render "form" %>

</div>

app/views/updates/index.html.erb
<div class="home-updates">
<% if user_signed_in? %>
  <h2>Update Feed</h2>
  <hr>

  <div class="post-new">
    <%= link_to "Post New Update", new_update_path, class: "button tiny round" %>
  </div>

  <div class="update">
    <% @updates.each do |u| %>
    <div class="update-topper panel">
      <h5><%= u.user.profile_name %>:</h5>
      <%= "Posted " + time_ago_in_words(u.created_at) + " ago" %>

      <p class="panel callout radius"><%= u.content %></p>
    </div>

    <div class="options">
      <ul class="ops sub-nav">
        <li>
          <%= link_to "Show", u, class: "warning tiny button radius" %>
        </li>
        <li class="admin">
          <%= link_to "Edit", edit_update_path(u), class: "secondary tiny button radius" %>
        </li>
        <li class="admin">
          <%= link_to "Destroy", u, method: :DELETE, data: { confirm: "Are you sure?" }, class: "alert tiny button radius" %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>

<% else %>

  <br>
  <div class="row">
    <%= link_to "Sign In", new_user_session_path, class: "button radius small-centered columns" %>
    <%= link_to "Join Us", new_user_registration_path, class: "button radius small-centered columns" %>
  </div>
<% end %>
</div>

app/views/updates/new.html.erb
<div class="write-update">
  <h2>Write New Update</h2>
  <hr>

  <div class="back">
    <%= link_to "Back", updates_path, class: "button tiny round" %>
  </div>

  <%= render "form" %>

</div>

app/views/updates/show.html.erb
<div class="show-update">
<% if user_signed_in? %>
  <h2>Show Update</h2>
  <hr>

  <div class="back">
    <%= link_to "Back", updates_path, class: "button tiny round" %>
  </div>

  <div class="update">
    <div class="update-topper panel">
    <h5><%= @update.user.profile_name %> –
    <em><%= @update.user.full_name %></em>:</h5>
    <%= "Posted " + time_ago_in_words(@update.created_at) + " ago" %>

    <p class="panel callout radius"><%= @update.content %></p>
    </div>
  </div>

  <div class="options">
    <ul class="ops sub-nav">
      <% if signed_in? && @update.user == current_user %>
        <li class="admin">
          <%= link_to "Edit", edit_update_path(@update), class: "warning tiny button radius" %>
        </li>
        <li class="admin">
          <%= link_to "Destroy", @update, method: :delete, data: { confirm: "Are you sure?" }, class: "alert tiny button radius" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>